[build]
  publish = "public"

[dev]
  port = 3000

[functions]
  external_node_modules = ['express']
  node_bundler = 'esbuild'
  directory = "functions"
  included_files = ["data/**"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"
