[build]
  publish = "public"

[dev]
  port = 3000

[functions]
  node_bundler = 'esbuild'
  directory = "functions"
  included_files = ["data/**"]

[images]
  remote_images = ["https://media.licdn.com/.*"]
